# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ac2559a3-6472-4a09-82f5-0a0dd902c76f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8c759ce5-417b-447f-988f-4ae2bf5e3f96".device = "/dev/disk/by-uuid/8c759ce5-417b-447f-988f-4ae2bf5e3f96";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A711-3E4F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/jay/games" =
    { device = "/dev/disk/by-uuid/3ed9cd61-5489-49a8-ba8c-94d2bb0fb649";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  fileSystems."/home/jay/secondary" =
    { device = "/dev/disk/by-uuid/7d836b86-c113-4f75-a151-fcc97d792432";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  fileSystems."/home/jay/external_hdd" =
    { device = "/dev/disk/by-uuid/409613A09613960E";
      fsType = "ntfs";
      options = [ "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8249bfb2-89f4-46ad-bc42-6ecfefcf75fc"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
